### PR TITLE
Add the option to override the upgrade delay on the CLI

### PR DESCRIPTION
**Pull request by offbyone**
I have a timed task that does this weekly, but I also want the ability
to upgrade immediately sometimes. This adds a `-a` flag that sets the
number of seconds to that number, which I can then set to zero.

### CODE REVIEW

**Comment by michealespinola** [comment]
This is something I have already written some code for. Its getopt (not getopts, but is similar. I had been holding off integrating it because of config file changes that I was also finalizing. I appreciate the effort you have made here, and will push up my schedule to get these changes made.

**Comment by offbyone** [comment]
That's perfect, thanks! I'll maintain the patch on my end until you have the time.

**Comment by michealespinola** [comment]
Sounds like a plan. I'll make certain that this option is in the next release.

**Comment by michealespinola** [comment]
Its been a while, but '-a' has been added as a getopts option. It should continue to work as previously discussed, and as such has been added to the next release.

**Review by michealespinola — APPROVED** [review]
Code works but required some modification to fit more appropriately with existing code redirections for logging and shellcheck compliancy. Code will be merged and then modified with required changes.

**Pull request merged**
