### PR TITLE
Adding DSM 7 compatibility

### PR DESCRIPTION
**Pull request by cmatte**
Plex now officially releases DSM 7 compatible packages, therefore adapted the script to the new version.

### CODE REVIEW

**Comment by Nedlinin** [comment]
As mentioned in #4 , this doesn't quite work.  I suspect it is because the script doesn't properly detect it installed after the fact.  Looks like you use the PackageName variable in a few places but missed some spots.  Specifically, line 290, 294 and 300

**Comment by cmatte** [comment]
> As mentioned in #4 , this doesn't quite work. I suspect it is because the script doesn't properly detect it installed after the fact. Looks like you use the PackageName variable in a few places but missed some spots. Specifically, line 290, 294 and 300

@Nedlinin exactly that - if only I had read your suggestion before trying to fix it! This is fixed in the new 3.0.4 :)

**Review by cmatte — COMMENTED** [review]
Be warned of https://forums.plex.tv/t/synology-dsm-7-build-41882-breaking-changes/719740/51 .

**Comment by tillkruss** [comment]
I've used this PR to update to `1.23.3.4707`, but now I have to "Allow Fallback to Insecure Connections".

How can I fix this?

**Comment by Nedlinin** [comment]
> I've used this PR to update to `1.23.3.4707`, but now I have to "Allow Fallback to Insecure Connections".
> 
> How can I fix this?

That'd be outside the goal of this PR.  You'll have to ask on the Plex forums as, perhaps, they've introduced a small bug in that version?

I'm on 1.23.3.4712 myself and do not appear to have this issue.

**Comment by tillkruss** [comment]
@Nedlinin: I've downloaded the `1.23.3.4707` `.spk` file for DSM7 from plex.tv, installed it manually and secure connections work again, so it might be an issue with this PR 🤷

**Comment by randomguy1991** [comment]
Tested the script and seems to be working well! No errors. If logs needed, let me know!

**Comment by cmatte** [comment]
Thanks all for the feedback. I have been testing this on the latest DSM 7.0-41890 without any major issues. I have experienced twice now that the package was stopped after an upgrade, therefore I've added a 10s waiting time to the script between installation and start, I will be able to confirm when the next update is available if this resolved. v. 3.0.6 below.
Has anyone else experienced the same?

**Comment by Nedlinin** [comment]
> Has anyone else experienced the same?

Mine has always started back up with no issue.

What model do you have? Wonder if it's a speed of the processor thing or just an overall system load problem?  Mine is scheduled for 3AM when the system will always be basically completely idle. 918+ model.


I think if the sleep ends up staying that adding a config option to enable it (or I suppose supply a sleep value) would be nice.  That way I could have mine sleep for only 1 second as it doesn't seem necessary on my end but you could use 10 and someone else could use 30 if desired.

**Comment by seanhamlin** [comment]
Giving this a whirl on my 918+. The script runs, no new versions found. I guess the test will be when a new version is released. Thanks for your work on this!

**Comment by smosse** [comment]
Just tried it on my 918+with DSM7.  the script found an update but was too new. Had to change day from 7 to 2 in config.ini and then everything worked.
Good job ! and Thanks !

**Comment by cmatte** [comment]
@michealespinola just checking if you wanted to include the latest DSM7 changes :)

**Pull request closed without merging**
